### ISSUE TITLE
Capture and translate github's webhook

### ISSUE THREAD

**Issue by gianarb** [gianarb/com.gianarb.thumber#1]
https://developer.github.com/v3/activity/events/types/#pullrequestevent

From this payload try to create an object like:

```yml
PullRequest:
    - repository:
        - id
        - owner/project
     - pr_id
     - []comment
     - []label
```
